webapp/chat/views.py
from webapp import app
from flask import Blueprint, render_template, url_for, request
from flask_login import login_user, current_user, logout_user, login_required
from webapp.models import User
from webapp import socketio
from flask_socketio import send, emit
from time import localtime, strftime
from flask import current_app
import os

chating = Blueprint('chating',__name__)



@chating.route('/chat')
def chat():

    return render_template('chat.html', username=current_user.username)


@socketio.on('message')
def message(data):

    print(data)

    send({'msg' : data['msg'], 'username' : data['username'], 'time_stamp' : strftime('%H:%M', localtime()), 'profile' : 'static/profile_pics/' + current_user.profile_image})

webapp/core/views.py
from flask import render_template, url_for, abort, redirect, Blueprint, request, jsonify
from webapp import db
from flask import current_app
import requests
import json
from webapp.users.forms import LoginForm
from webapp.models import Leader, Daily, News, Playerdata, Statistics
from webapp.core.forms import SelectForm
from flask_login import current_user, login_required
from selenium import webdriver
from datetime import datetime, date, timedelta
import time
import praw


core = Blueprint('core',__name__)

@core.route('/')
def index():

    #var since created with datetime for querying the database for last 24 hours
    since = datetime.now() - timedelta(days=1)
    since.strftime('%y%d%m')

    #filtering table Daily with filter .date > since
    day = db.session.query(Daily).filter(Daily.date > since).all()

    return render_template('index.html', day=day)

@core.route('/player')
@login_required
def player_info():

    #One of first views i created it can be used to show historical data of players

    myPlayer = Leader.query.all()
    return render_template('player_info.html', myPlayer=myPlayer)


@core.route('/news')
@login_required
def news():

    #Using the datetime to query table for last 24 hours.
    since = datetime.now() - timedelta(hours=12)
    since.strftime('%y%d%m')

    newsDay = db.session.query(News).filter(News.date > since).all()


    return render_template('playernews.html', newsDay=newsDay)

@core.route('/highlights', methods=["GET", "POST"])
@login_required
def highlights():

    #Using the youtube API i get the last 12 videos that are related to nba !

    search_url = 'https://www.googleapis.com/youtube/v3/search'
    video_url = 'https://www.googleapis.com/youtube/v3/videos'

    videos = []

    search_params = {
        'key' : current_app.config['YOUTUBE_API_KEY'],
        'q' : 'nba highlights',
        'part' : 'snippet',
        'maxResults' : 12,
        'type' : 'video'
        }

    r = requests.get(search_url, params=search_params)

    video_ids = []

    rezultat = r.json()['items']


    for rez in rezultat:
        video_ids.append(rez['id']['videoId'])

    video_params = {
            'key' : current_app.config['YOUTUBE_API_KEY'],
            'id' : ','.join(video_ids),
            'part' : 'snippet,contentDetails',
            'maxResults' : 12
        }

    r = requests.get(video_url, params=video_params)
    results = r.json()['items']

    for result in results:
            video_data = {
                'id' : result['id'],
                'url' : f'https://www.youtube.com/watch?v={ result["id"] }',
                'thumbnail' : result['snippet']['thumbnails']['high']['url'],

                'title' : result['snippet']['title'],
            }

            videos.append(video_data)



    return render_template('highlights.html', videos=videos)

@core.route('/charts', methods=['GET', 'POST'])
@login_required
def charts():

    #Using Playerdata table to fill the select fields in HTML.

    myPlayer = Playerdata.query.all()
    return render_template('charts.html', myPlayer=myPlayer)


@core.route('/process' , methods=['GET','POST'])
def process():
    """ Setting up processing for charts.js, simply check for values inside the
    'selectFieldone', and 'selectFieldtwo' once i get then i use the values wich
    are esentially the ids of players i query the Statistics table to return jsonify
    data and feed the charts.js"""

    since = datetime.now() - timedelta(hours=20)
    since.strftime('%y%d%m')

    data = request.form['selectFieldone']
    data_two = request.form['selectFieldtwo']

    if data and data_two:
        data = int(data)
        player = Statistics.query.filter_by(players_id=data).filter(Statistics.date > since).first()
        player_two = Statistics.query.filter_by(players_id=data_two).filter(Statistics.date > since).first()


        return jsonify({"player_o": [player.gamesplayed, player.averageMin, player.fgm,
        player.fga, player.fgpct, player.treepm, player.treeatt, player.treepct,
        player.ftm, player.fta, player.ftpct, player.reb, player.ast, player.stl,
        player.blk, player.tov, player.ppg], 'player_t' : [player_two.gamesplayed,
        player_two.averageMin, player_two.fgm,player_two.fga, player_two.fgpct,
        player_two.treepm, player_two.treeatt, player_two.treepct,
        player_two.ftm, player_two.fta, player_two.ftpct, player_two.reb,
        player_two.ast, player_two.stl, player_two.blk, player_two.tov, player_two.ppg],
        'player_onename': player.stats.name, 'player_twoname' : player_two.stats.name,
        'first' : player.stats.pict, 'second' : player_two.stats.pict})


@core.route('/update')
@login_required
def update():
    """ Using selenium to scrape of scores every day from nba.com , i know its
    a great way to feed your website due to fact that small HTML changes can break
    down the script"""

    browser = webdriver.Chrome('C:\\Users\\User\\Desktop\\chromedriver')

    browser.get('https://www.nba.com/scores#/')


    full_scores = browser.find_elements_by_xpath('//span[@class="current_score"]')
    team_names =  browser.find_elements_by_xpath('//div[@class="score-tile__team-name"]')
    score_img = browser.find_elements_by_tag_name('img')

    #Using bulk session to import whole object!
    score_list = []
    for score, team, img in zip(full_scores, team_names, score_img):
        score_list.append({
            'name': team.text,
            'score': score.text,
            'link': img.get_attribute('src'),
        })

    db.session.bulk_insert_mappings(Daily, score_list, return_defaults=True)
    db.session.commit()

    browser.close()

    return redirect(url_for('core.index'))


@core.route('/newsupdate')
@login_required
def news_update():
    browser = webdriver.Chrome('C:\\Users\\User\\Desktop\\chromedriver')

    browser.get('https://www.rotoworld.com/sports/nba/basketball')


    links = []
    player_name = browser.find_elements_by_xpath('//div[@class="player-news-article__profile"]')
    titles_text = browser.find_elements_by_xpath('//div[@class="player-news-article__title"]')
    text = browser.find_elements_by_xpath('//div[@class="player-news-article__summary"]')
    images = browser.find_elements_by_tag_name('img')



    for img in images:
        links.append(img.get_attribute('src'))

    links2= links[1:]
    news_list = []
    for title, heading, article, links in zip(titles_text, player_name, text, links2[1::2]):
        news_list.append({
            'title': title.text,
            'heading': heading.text,
            'article': article.text,
            'pic' : links
        })

    db.session.bulk_insert_mappings(News, news_list, return_defaults=True)
    db.session.commit()

    browser.close()

    return redirect(url_for('core.news'))

@core.route('/playersupdate', methods=["GET"])
@login_required
def players_update():

    request_headers = {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
    'Accept-Encoding': 'gzip, deflate',
    'Accept-Language': 'en-US,en;q=0.8',
    'Connection': 'keep-alive',
    'Host': 'stats.nba.com',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36'
    }
    url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=PerGame&Scope=S&Season=2019-20&SeasonType=Regular+Season&StatCategory=PTS'
    response = requests.get(url, headers = request_headers)
    stat = response.json()
    results = stat['resultSet']
    need = results['rowSet']
    #The json format was bit weird but i had to loop over ['rowSet'] to get the data i wanted

    for item in need:
        # I have already set up Playerdata table with player names and json_ids
        player = db.session.query(Playerdata).filter_by(json_id=item[0]).first()

        #If there is a player i just update the Statistics table that i have relationship with
        if player:
            new = Statistics(
            players_id = player.id,
            team = item[3],
            gamesplayed=item[4],
            averageMin=item[5],
            fgm=item[6],
            fga=item[7],
            fgpct=item[8],
            treepm=item[9],
            treeatt=item[10],
            treepct=item[11],
            ftm=item[12],
            fta=item[13],
            ftpct=item[14],
            oreb=item[15],
            dreb=item[16],
            reb=item[17],
            ast=item[18],
            stl=item[19],
            blk=item[20],
            tov=item[21],
            ppg=item[22])

            db.session.add(new)
        #Add a new player to Playerdata table if some new player enters the league
        if not player:
            create = Playerdata(
            name=item[2],
            json_id=item[0]
            )

            db.session.add(create)

        db.session.commit()


    return redirect(url_for('core.index'))

@core.route('/currentyear', methods=['GET', 'POST'])
@login_required
def current_year():

    form = SelectForm()

    since = datetime.now() - timedelta(days=1)
    since.strftime('%y%d%m')

    page = request.args.get('page', 1, type=int)
    today = db.session.query(Statistics).filter(Statistics.date > since).paginate(page=page, per_page=30)

    #If i person decide to search for a player by his name
    if request.method == 'POST' and  form.validate_on_submit():
        one1 = Playerdata.query.filter_by(name=form.select1.data).first()
        #I take the name from form and query the table and return that players id to view core.one
        return redirect(url_for('core.one', one1=one1.id))

    return render_template('playertoday.html', today=today, form=form)

@core.route('/one/<one1>', methods=["POST", "GET"])
@login_required
def one(one1):
    """ Taking the one1 var that contains players_id and i query the tables to

webapp/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from webapp import db
from webapp.models import User
from webapp.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from webapp.users.userpic import add_profile_pic

users = Blueprint('users',__name__)



#register
@users.route('/register', methods=["GET", "POST"])
def register():
    """ Simple register view that updates the database after submiting the form"""

    form= RegistrationForm()

    if form.validate_on_submit():

        user = User(email = form.email.data,
                    username = form.username.data,
                    password = form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('You have sucesfully registered your account')

        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)

#login
@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()

    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Log in success!')

            next = request.args.get('next')

            if next == None or not next[0]=='/':

                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html', form=form)




#logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))
#acccount
@users.route('/account', methods=["GET", "POST"])
@login_required
def account():
    """ A view that allows you to change username and profile picture"""

    form = UpdateUserForm()

    if form.validate_on_submit():
        print(form)
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)

webapp/templates/account.html
{% extends 'base.html' %}
{% block content %}

<div align=center>


<div class="jumbotron">
  <div align='center'>
    <h1 >Welcome to the page for {{current_user.username}}</h1>
    <img align='center' src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}">
    <p>{{ current_user.email }}</p>
  </div>
</div>
<div class="container">
  <form  method="POST" action = "" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.username.label(class="form-group") }}
      {{form.username(class='form-control')  }}
    </div
    <div class="form-group">
      {{ form.email.label(class="form-group") }}
      {{form.email(class='form-control')  }}
    </div>
    <div class="form-group">
      {{ form.picture.label(class="form-group") }}
      {{ form.picture(class="form-control-file") }}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>
</div>

{% endblock content %}

webapp/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
    <script src="http://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js" integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>




    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">NBA</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('core.index') }}">Home <span class="sr-only">(current)</span></a>
      </li>
      {% if current_user.is_authenticated %}

      <li class="nav-item">
      <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
    </li>
  </li>
  <li class="nav-item">
  <a class="nav-link" href="{{url_for('chating.chat')}}">Chat Hub</a>
</li>

<li class="nav-item dropdown">
   <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
     Dropdown
   </a>
   <div class="dropdown-menu" aria-labelledby="navbarDropdown">
     <a class="dropdown-item" href="{{url_for('core.current_year')}}">League Leaders</a>
     <a class="dropdown-item" href="{{url_for('core.charts')}}">Head to Head</a>
     <a class="dropdown-item" href="{{url_for('core.player_info')}}">Leaders History</a>
     <div class="dropdown-divider"></div>
     <a class="dropdown-item" href="{{url_for('users.logout')}}">Log Out</a>
   </div>

</div>


  </div>



      {% else %}
      <li class="nav-link"><a href="{{url_for('users.login')}}">Log In</a></li>
      <li class="nav-link"><a href="{{url_for('users.register')}}">Register</a></li>
      {% endif %}

  </ul>

</nav>


  </body>
  {% block content %}

  {% endblock %}
</html>

webapp/templates/charts.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-chart">

      </div>



    <script>
    function showChart(value) {
        var myBarChart = new Chart($("#myChart"), {
            type: 'bar',
            data: {
              labels: ["Games Played" , "Average Min", "FGM", "FGA", "FG %",
             "3PM", "3PA", "3PT %", "FTM", "FTA", "FT %", "REB", "AST", "STL", "BLK", "TOV", "PPG"],
                datasets: [{
                    label: value.player_onename,
                    data: value.player_o,
                    backgroundColor:  '#26B99A'
                  },
                  {
                    label: value.player_twoname,
                    data: value.player_t,
                    backgroundColor: "#03586A"

                }]
            },
            options: {
                responsive: true,
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
    }
    $(document).ready(function() {
        $('#chart-form').on('submit', function(event) {
            $.ajax({
                data: {
                    selectFieldone: $('#selectFieldone').val(),
                    selectFieldtwo: $('#selectFieldtwo').val(),

                },
                type: 'POST',
                url: '/process',
                success: function(result) {
                    showChart(result);
                    $("#isplayerone").attr("src", result.first);
                    $("#isplayertwo").attr("src", result.second);

                }
            });
            event.preventDefault();
        });
    });
    </script>

    <div class="container">
  <canvas  aling='center' id="myChart" width="500" height="300"></canvas>
</div>
<div class="container" align='center'>
  <img src="" id="isplayerone">
  VS
  <img src="" id='isplayertwo'>
</div>

<div class="container" align='center'>
  <form id="chart-form" class="form-group">
      <label for="selectField">Select a player</label>
      <select class="form-control" id="selectFieldone">
        {% for player in myPlayer %}
        <option value="{{player.id}}">{{player.name}}</option>
        {% endfor %}
      </select>
      <label for="selectField">Select a player</label>
      <select class="form-control" id="selectFieldtwo">
        {% for player in myPlayer %}
        <option value="{{player.id}}">{{player.name}}</option>
        {% endfor %}
      </select>
      <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</form>


</div>
{% endblock %}

webapp/templates/chat.html
{% extends 'base.html' %}

{% block content %}
<style>
 div.bubble {
   background-color: #ddd;
    padding: 5px 10px;
    border-radius: 10px;
    color: #555;
    margin-bottom: 5px;
    border: 2px solid Black;
   }
     .bubble img {
       position: right;
       max-width: 60px;
       width: 100%;
       margin-right: 20px;
       border-radius: 70%;

     }
     .message {
       color:black;
     }

     .right {
             position: absolute;
             overflow: auto;
             left: 40%;
             right: 0;
             top: 10;
             bottom: 30px;
             width: 70%;
             height: 90%;
         }
      .left {
             position: absolute;
             overflow: auto;
             right: 60%;
             left: 0;
             top: 10;
             bottom: 30px;
             background: #00000;
             height: 90%;
         }
      .col-sm-4{
        position: absolute;
        top : 20;
      }
</style>

<div class="container">
    <div class="right">
      <div class="col-sm-8">
          <div id="display-message" class='message-holder'></div>
        </div>
      </div>
    </div>
    <div class="left">
      <div class="col-sm-4">
        <b >Type your message below</b>
        <div style="padding-top: 5px;"></div>
        <input type="text" id='user_message' placeholder="Messages">
        <div style="padding-top: 5px;"></div>
        <button type="submit" id='send_message'class="btn btn-secondary"><span class="glyphicon glyphicon-send"></span> Send</button>
      </div>
    </div>
  </div>
</div>

<script >
const username= `{{username}}`;
var socket = io();
  socket.on('message', data => {
  const chatBox = document.getElementById("display-message");
  const messageContainer = document.createElement('div');
  messageContainer.classList.add('bubble');
  const username = document.createElement('span');
  const message = document.createElement('span');
  const time_stamp = document.createElement('span');
  const image = document.createElement('img')
  image.setAttribute('src', data.profile)


  username.classList.add("username")
  username.innerHTML = data.username + '<br>';

  message.classList.add("message");
  message.innerHTML = data.msg + '<br>';

  time_stamp.classList.add('time_stamp')
  time_stamp.innerHTML = data.time_stamp




  messageContainer.appendChild(username);
  messageContainer.appendChild(message);
  messageContainer.appendChild(time_stamp);
  messageContainer.appendChild(image)

  chatBox.appendChild(messageContainer)

});
socket.on('some-event', data => {
  console.log(data)
});
document.querySelector('#send_message').onclick = () =>{
  socket.send({'msg' : document.querySelector('#user_message').value,
  'username' : username});
};

let message = document.getElementById('user_message');
message.addEventListener("keyup", function(event){
  if (event.keyCode==13){
    document.getElementById("send_message").click();
  }
  document.getElementById("send_message").reset();
});

</script>

{% endblock %}

webapp/templates/highlights.html
{% extends 'base.html' %}
{% block content %}
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='album.css') }}" rel="stylesheet">
  </head>
  <body>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        {% for video in videos %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{ video.thumbnail }}" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"></img>
            <div class="card-body">
              <p class="card-text">{{ video.title }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a type="button" href="{{ video.url }}" class="btn btn-sm btn-outline-secondary">View</a>
                </div>

              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock content %}

webapp/templates/index.html
{% extends 'base.html' %}


{% block content %}
{% if current_user.is_authenticated %}

<h1 align='center'>
<a href="{{url_for('core.highlights')}}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Highlights</a>
<a href="{{url_for('core.news')}}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">News</a>
</h1>

{% endif %}

{% for daily in day %}
<ul>
<div class="" align='center' height="400px" width='300px'>
  {{daily.name}} {{daily.score}}
  <img src="{{daily.link}}" alt="" width="50px" height="50px">

</div>
</ul>
{% endfor %}

{% endblock %}

webapp/templates/playertoday.html
{% extends 'base.html' %}

{% block content %}
<style>
#customers {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #26B99A;
  color: white;
}
</style>

<form align=center method="post">

  {{form.hidden_tag()}}
  {{form.select1.label}}{{form.select1(placeholder='Type in Full Name')}}
  {{form.submit()}}

</form>




  <h2 align = 'center'>LEAGUE LEADERS 19/20</h2>
<div class="container">


  <table id="customers">
    <tr>
      <th>Name</th>
      <th>Team</th>
      <th>GP</th>
      <th>MPG</th>
      <th>FGM</th>
      <th>FGA</th>
      <th>FG%</th>
      <th>3 PM</th>
      <th>3 ATT</th>
      <th>3 PT%</th>
      <th>FTM</th>
      <th>FTA</th>
      <th>FT%</th>
      <th>OREB</th>
      <th>DREB</th>
      <th>REB</th>
      <th>AST</th>
      <th>STL</th>
      <th>BLK</th>
      <th>TOV</th>
      <th>PPG</th>
    </tr>
    {% for player in today.items %}
    <tr>
      <td>{{player.stats.name}}</td>
      <td>{{player.team}}</td>
			<td>{{player.gamesplayed}}</td>
      <td>{{player.averageMin}}</td>
      <td>{{player.fgm}}</td>
      <td>{{player.fga}}</td>
      <td>{{player.fgpct}}</td>
      <td>{{player.treepm}}</td>
      <td>{{player.treeatt}}</td>
      <td>{{player.treepct}}</td>
      <td>{{player.ftm}}</td>
      <td>{{player.fta}}</td>
      <td>{{player.ftpct}}</td>
      <td>{{player.oreb}}</td>
      <td>{{player.dreb}}</td>
      <td>{{player.reb}}</td>
      <td>{{player.ast}}</td>
      <td>{{player.stl}}</td>
      <td>{{player.blk}}</td>
      <td>{{player.tov}}</td>
      <td>{{player.ppg}}</td>

    </tr>
    {% endfor %}

  </table>
  </div>

	<nav aria-label="Page navigation example">
	  <ul class="pagination justify-content-center">
	    {# http://flask.pocoo.org/snippets/44/ #}

	    {% for page_num in today.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
	            {% if today.page == page_num %}
	              <li class="page-item disabled">
	                <a class="page-link" href="{{ url_for('core.current_year', page=page_num) }}">{{ page_num }}</a></li>
	              </li>
	            {% else %}
	              <li class="page-item"><a class="page-link" href="{{ url_for('core.current_year', page=page_num) }}">{{ page_num }}</a></li>
	            {% endif %}
	    {% endfor %}
	</nav>


</div>


{% endblock %}